# infra/ansible/dev/handlers/main.yml
- name: Restart docker-compose stack
  ansible.builtin.command: >
    docker-compose -f /home/{{ ansible_user }}/project/docker-compose.yml up -d
  args:
    chdir: /home/{{ ansible_user }}/project
