name: Build & Push Pipeline

on:
  workflow_call:
    outputs:
      image_tag:
        description: "Docker image tag built and pushed"
        value: ${{ jobs.build.outputs.image_tag }}

env:
  IMAGE_NAME: alqoseemi/yelpcamp
  GITHUB_SHA_SHORT: ${{ github.sha }}
  IMAGE_TAG: ${{ github.run_number }}-${{ github.sha }}

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.vars.outputs.image_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: vars
        run: echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Define short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA_SHORT:0:7}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:${{ steps.vars.outputs.image_tag }} .

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push $IMAGE_NAME:${{ steps.vars.outputs.image_tag }}

