name: Build & Push Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

env:
  IMAGE_NAME: alqoseemi/yelpcamp
  SHORT_SHA: ${{ github.sha }}
  IMAGE_TAG: ${{ github.run_number }}-${{ github.sha }}

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      image_tag: ${{ steps.vars.outputs.image_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: vars
        run: echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Define short SHA
        run: echo "SHORT_SHA=${SHORT_SHA:0:7}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push $IMAGE_NAME:$IMAGE_TAG

      

