name: Build & Deploy Pipeline

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: alqoseemi/yelpcamp

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.vars.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4

      - id: vars
        run: echo "image_tag=${{ github.run_number }}-${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:${{ steps.vars.outputs.image_tag }} .

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push $IMAGE_NAME:${{ steps.vars.outputs.image_tag }}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-ansible

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Retrieve secrets from AWS Secrets manager
        run: |
          SECRET=$(aws secretsmanager get-secret-value --secret-id yelpcamp/env --query SecretString --output text)
          echo "$SECRET" > .env
          cat .env >> $GITHUB_ENV

      - name: Set up EC2 SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 13.221.40.129 >> ~/.ssh/known_hosts
          
      - name: Generate .env from AWS Secrets Manager
        run: |
          SECRET=$(aws secretsmanager get-secret-value \
            --secret-id yelpcamp/env \
            --query SecretString \
            --output text)
          echo "$SECRET" | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > .env

      - name: Run Ansible Playbook (Dev)
        run: ansible-playbook -i infra/ansible/inventory/dev.ini infra/ansible/playbook-dev.yaml --extra-vars "docker_image=${{ needs.build.outputs.image_tag }} dockerhub_username=${{ secrets.DOCKERHUB_USERNAME }} dockerhub_token=${{ secrets.DOCKERHUB_TOKEN }} app_port=3000"

  deploy-stage:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: stage
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-ansible
      - run: ansible-playbook -i infra/ansible/inventory/stage.ini infra/ansible/playbook-stage.yaml --extra-vars "docker_image=${{ needs.build.outputs.image_tag }}"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-stage
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-ansible
      - run: ansible-playbook -i infra/ansible/inventory/prod.ini infra/ansible/playbook-prod.yaml --extra-vars "docker_image=${{ needs.build.outputs.image_tag }}"
