name: Deploy with Ansible

on:
  workflow_run:
    workflows: [""]
    types:
      - completed

jobs:
  setup-ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ansible + linting tools
        run: pip install ansible ansible-lint detect-secrets

      - name: Install required collections
        run: ansible-galaxy install -r requirements.yml

  deploy-dev:
    runs-on: ubuntu-latest
    needs: setup-ansible
    steps:
      - uses: actions/checkout@v4
      - name: Run Ansible Playbook (Dev)
        run: ansible-playbook -i inventory/dev.ini playbook-dev.yml

  deploy-stage:
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
      - uses: actions/checkout@v4
      - name: Run Ansible Playbook (Stage)
        run: ansible-playbook -i inventory/stage.ini playbook.yml

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-stage
    steps:
      - uses: actions/checkout@v4
      - name: Run Ansible Playbook (Prod)
        run: ansible-playbook -i inventory/prod.ini playbook.yml
