name: Deploy Pipeline

on:
  workflow_run:
    workflows: ["Build & Push Pipeline "]   # ðŸ‘ˆ link to your Build workflow
    types:
      - completed

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-ansible   # ðŸ‘ˆ call composite action

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Retrieve secrets from AWS Secrets Manager
        run: |
          SECRET=$(aws secretsmanager get-secret-value --secret-id yelpcamp/env --query SecretString --output text)
          echo "$SECRET" > .env
          cat .env >> $GITHUB_ENV

      - name: Set up EC2 SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 13.221.40.129 >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook (Dev)
        run: ansible-playbook -i inventory/dev.ini playbook-dev.yml

  deploy-stage:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: stage
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-ansible
      - run: ansible-playbook -i inventory/stage.ini playbook.yml

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-stage
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-ansible
      - run: ansible-playbook -i inventory/prod.ini playbook.yml

